### ISSUE TITLE
user-can-create-a-profile

### ISSUE THREAD

**Issue by josh-choi94** [josh-choi94/code-journal#1]
# Feature

User can create a profile.

## Issue Template

Open a new Issue on your GitHub repository with the title **User can create a profile** and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

```md
## 💰 Motivation

Users like to personalize things! 😄

## 📐 Plan

Create a responsive form for users to enter their profile details into and save their data to local storage.

## 🖼️ Wireframe

![user can create a profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-create-a-profile.png)

## ✅ Task List

- [ ] Pick a nice font pair from Google Fonts for headings and body text.
- [ ] Pick a nice accent color.
- [ ] Create a simple, polished header in HTML and CSS that shows the name of the application.
- [ ] Create a simple, polished form in the HTML and CSS that shows a placeholder image for the avatar.
- [ ] Apply fonts to the heading, labels, and form inputs.
- [ ] Check to make sure that the form looks good on mobile and desktop.
- [ ] Make all form inputs `required`.
- [ ] Make the `name` attributes of the form input elements match the keys of the profile data model.
- [ ] Listen for `'input'` events on the avatar url input.
- [ ] Update the avatar preview image's `src` when the avatar url input changes.
- [ ] Listen for `'submit'` events on the form.
- [ ] Assign all of the form's values into the profile data model when the form is submitted.
- [ ] Reset the form inputs when the form is submitted.
- [ ] Reset the avatar preview image when the form is submitted.
- [ ] Make sure that the user's data is persisted to local storage between reloads.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again.

```

## HINTS

- You can size an image's `height` without warping it with the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties.

## Workflow

Be sure to stick with [the workflow](https://github.com/Learning-Fuze/code-journal-instructions#workflow) while building.

## Example

This is just an example in case you need it. You should primarily base your implementation on the wireframe in your GitHub Issue. Your app does not have to look exactly like this one, but **the layout should match the wireframe** and it should be **visually appealing**.

![user can create a profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/code-journal/user-can-create-a-profile.gif)
