### ISSUE TITLE
user-can-update-their-profile

### ISSUE THREAD

**Issue by josh-choi94** [josh-choi94/code-journal#3]
# Feature

User can update their profile.

## Issue Template

Open a new Issue on your GitHub repository with the title **User can update their profile** and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

```md
## 💰 Motivation

Users will want to change their profile information to suit their mood.

## 📐 Plan

Allow users to navigate between their profile and the form to edit their profile details.

## 🖼️ Wireframe

![user can update their profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-update-their-profile.png)

## ✅ Task List

- [ ] Update the view swapping function to pre-populate the profile form and avatar preview when showing the `'edit-profile'` view.
- [ ] Test the view swapping function by hand in the browser console.
- [ ] Update the profile rendering function to include a link styled as a button with an `href="#"` and a `data-view="edit-profile"`.
- [ ] Add a `'click'` listener to the `document` that exits immediately if a link was not clicked.
  - [ ] If a link _was_ clicked, show the matching view using the view swapping function.
- [ ] Add link to the navbar with an `href="#"` and a `data-view="profile"`.
- [ ] Verify that clicking the profile link navigates away from the profile form.
- [ ] Block the user from going to the `'profile'` view if they have never saved a `username`.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test the user flow in a private browsing tab.
- [ ] Fix all bugs.

```

## Hints

- This feature sets up [event delegation](https://davidwalsh.name/event-delegate) that is used in the rest of the features.

## Workflow

Be sure to stick with [the workflow](https://github.com/Learning-Fuze/code-journal-instructions#workflow) while building.

## Example

This is just an example in case you need it. You should primarily base your implementation on the wireframe in your GitHub Issue. Your app does not have to look exactly like this one, but **the layout should match the wireframe** and it should be **visually appealing**.

![user can update their profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/code-journal/user-can-update-their-profile.gif)
