### ISSUE TITLE
user-can-view-their-entries

### ISSUE THREAD

**Issue by josh-choi94** [josh-choi94/code-journal#5]
# Feature

User can view their entries.

## Issue Template

Open a new Issue on your GitHub repository with the title **User can view their entries** and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

```md
## 💰 Motivation

Once a user records a journal entry, they'll want to revisit it again.

## 📐 Plan

Display the user's journal entries in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframe

![user can view their entries](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-view-their-entries.png)

## ✅ Task List

- [ ] Add an empty ordered list element to the `div[data-view="entries"]`.
- [ ] Add some dummy journal entries to the HTML and style them to match the wireframe.
- [ ] Check that the entries list looks good on both mobile and desktop screens.
- [ ] Define a function that takes a single journal entry object and returns a DOM tree that matches one of the example entries in the HTML.
- [ ] Create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [ ] Remove the example HTML entries once the user's entries are successfully being appended.
- [ ] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [ ] Clean up all unnecessary styling.
- [ ] Test the user flow in a private browsing tab.
- [ ] Fix all bugs.

```

## HINTS

- You can size an image's `height` without warping it with the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties.
- You can empty an HTML element by setting its [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) property to an empty string.
- The [`prepend()`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend) method can be used to add a DOM element to the beginning of its parent's children.

## Workflow

Be sure to stick with [the workflow](https://github.com/Learning-Fuze/code-journal-instructions#workflow) while building.

## Example

This is just an example in case you need it. You should primarily base your implementation on the wireframe in your GitHub Issue. Your app does not have to look exactly like this one, but **the layout should match the wireframe** and it should be **visually appealing**.

![user can view their entries](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/code-journal/user-can-view-their-entries.gif)
